<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.ws.konstpan.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="RefDataImplService" targetNamespace="http://service.ws.konstpan.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service.ws.konstpan.com/" elementFormDefault="unqualified" targetNamespace="http://service.ws.konstpan.com/" version="1.0">

  <xs:element name="getData" type="tns:getData"/>

  <xs:element name="getDataResponse" type="tns:getDataResponse"/>

  <xs:complexType name="getData">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="getDataResponse">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getData">
    <wsdl:part element="tns:getData" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getDataResponse">
    <wsdl:part element="tns:getDataResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RefData">
    <wsdl:operation name="getData">
      <wsdl:input message="tns:getData" name="getData">
    </wsdl:input>
      <wsdl:output message="tns:getDataResponse" name="getDataResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RefDataImplServiceSoapBinding" type="tns:RefData">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getData">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RefDataImplService">
    <wsdl:port binding="tns:RefDataImplServiceSoapBinding" name="RefDataImplPort">
      <soap:address location="http://localhost:8080/webservices-server/RefDataImpl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>